acount/urls.py
app_name = 'acount'

from django.contrib import admin
from django.urls import path
import acount.views
from django.contrib.auth.views import LogoutView



urlpatterns = [
    path('accounts/login/',acount.views.login_request,name='Login'),
    path('accounts/signup/',acount.views.register,name='Registro'),
    path('accounts/logout/', LogoutView.as_view(template_name='acount/logout.html'), name='Logout'),
    path('accounts/profile/edit', acount.views.editarPerfil, name="EditarPerfil"),
    path('accounts/profile/avatar',acount.views.editarAvatar,name="EditarAvatar"),
    path('accounts/profile', acount.views.verPerfil, name="VerPerfil"),

]

nquinterno_proy_final/urls.py
from django.contrib import admin
from django.urls import path, include
import web_ppal.views, acount.views
from django.contrib.auth.views import LogoutView
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web_ppal.urls', namespace='web_ppal')),
    path('', include('acount.urls', namespace='acount')),
]

urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

web_ppal/urls.py
app_name = 'web_ppal'
from django.urls import path
import web_ppal.views


urlpatterns = [
    path("",web_ppal.views.inicio, name="Inicio"),
    path("about/",web_ppal.views.aboutMe,name="AboutMe"),
    path("chat",web_ppal.views.ChatList.as_view(),name="Chat"),
    path("pages/",web_ppal.views.PostList.as_view(),name="List"),
    path(r'pages/(?P<pk>)',web_ppal.views.PostDetalle.as_view(),name="Detail"),
    path(r'^nuevo$',web_ppal.views.PostCreacion.as_view(),name="New"),
    path(r'^editar/(?P<pk>\d+)$',web_ppal.views.PostModificar.as_view(),name="Edit"),
    path(r'^borrar/(?P<pk>\d+)$',web_ppal.views.PostBorrar.as_view(),name="Delete"),
    path(r'^nuevoComentario/$',web_ppal.views.CommentCreacion.as_view(),name="NewComment"),
    path(r'^borrarComentario/(?P<pk>\d+)$',web_ppal.views.CommentBorrar.as_view(),name="DeleteComment"),
    path(r'^editarComentario/(?P<pk>\d+)$',web_ppal.views.CommentModificar.as_view(),name="EditComment"),
    path(r'^nuevoChat/$',web_ppal.views.ChatCreacion.as_view(),name="NewChat"),
    path(r'chat^(?P<pk>\d+)$',web_ppal.views.ChatDetalle.as_view(),name="DetailChat"),
    path(r'^EnviarMensaje/$', web_ppal.views.SendMessage.as_view(), name='send_message'),
]

web_ppal/models.py
from django.db import models
from acount.models import *
from django.utils import timezone
    
class Post(models.Model):
    autor_id = models.ForeignKey(User, on_delete=models.CASCADE)
    titulo = models.CharField(max_length=40)
    subtitulo = models.CharField(max_length=100, default="")
    texto = models.CharField(max_length=2500)
    imagen = models.ImageField(upload_to='posteos', null=True, blank = True,)
    fecha = models.DateTimeField(default=timezone.now)
 
    def __str__(self):
        return f"{self.autor_id} - {self.titulo}"

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comentario = models.TextField(max_length=500)
    fecha = models.DateTimeField(default=timezone.now)

class Chat(models.Model):
    usuario1 = models.ForeignKey(User,related_name='chats1' ,on_delete=models.CASCADE)
    usuario2 = models.ForeignKey(User,related_name='chats2',verbose_name='Destinatario',on_delete=models.CASCADE)
    fecha_creacion = models.DateTimeField(default=timezone.now)
    
    def __str__(self):
        return f"Chat de {self.usuario1} - {self.usuario2}"

class Mensaje(models.Model):
    chat = models.ForeignKey(Chat, on_delete=models.CASCADE, related_name='mensajes')
    emisor = models.ForeignKey(User, on_delete=models.CASCADE)
    mensaje = models.TextField(max_length=500)
    fecha_envio = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"mensaje de {self.emisor} - {self.mensaje}"

web_ppal/forms.py
from django import forms
from .models import *

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['titulo','subtitulo' ,'texto', 'imagen']

    def clean_imagen(self):
        imagen = self.cleaned_data.get('imagen')
        if imagen:
            if not imagen.name.endswith('.png'):
                raise forms.ValidationError("La imagen debe tener el formato PNG.")
        return imagen

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comentario']

class ChatForm(forms.ModelForm):
    class Meta:
        model = Chat
        fields = ['usuario2']

class MessageForm(forms.ModelForm):
    class Meta:
        model = Mensaje
        fields = ['mensaje']
        widgets = {
            'mensaje': forms.Textarea(attrs={'rows': 3}),
        }

web_ppal/views.py
from .models import *
from acount.models import * 
from django.shortcuts import render, redirect
from .forms import *
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
# importaciones para vistas basadas en clases
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from PIL import Image
import os
from django.conf import settings
import uuid


def inicio(request):
    return render(request,'web_ppal/home.html')

def aboutMe(request):
    return render(request,'web_ppal/aboutMe.html')

class PostList(ListView, LoginRequiredMixin):
    model = Post
    template_name = 'web_ppal/post_list.html'

class PostDetalle(DetailView, LoginRequiredMixin):
    model = Post
    template_name = 'web_ppal/post_detalle.html'

class PostCreacion(CreateView, LoginRequiredMixin):
    model = Post
    success_url = '../pages'
    form_class = PostForm
    
    def form_valid(self, form):
        form.instance.autor_id = self.request.user
        imagen = form.cleaned_data['imagen']
        if imagen:
            nombre_imagen = str(uuid.uuid4()) + '.' + imagen.name.split('.')[-1]

            img = Image.open(imagen)
            img = img.resize((1080, 1080))
            image_path = os.path.join(settings.MEDIA_ROOT, 'posteos', nombre_imagen)
            img.save(image_path)
            form.instance.imagen = os.path.join('posteos', nombre_imagen)
        return super().form_valid(form)

class PostModificar(UpdateView, LoginRequiredMixin):
    model = Post
    success_url = '../pages'
    form_class = PostForm

class PostBorrar(DeleteView, LoginRequiredMixin):
    model = Post
    success_url = '../pages/'

#Vistas para comentarios
class CommentCreacion(CreateView, LoginRequiredMixin):
    model = Comment
    success_url = '../pages/'
    form_class = CommentForm
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.post_id = self.request.GET.get('post_id')
        return super().form_valid(form)

class CommentModificar(UpdateView, LoginRequiredMixin):
    model = Comment
    success_url = '../pages/'
    form_class = CommentForm

class CommentBorrar(DeleteView, LoginRequiredMixin):
    model = Comment
    success_url = '../pages/'

#Vistas para Chats
class ChatCreacion(CreateView, LoginRequiredMixin):
    model = Chat
    success_url = '../chat'
    form_class = ChatForm
    
    def form_valid(self, form):
        form.instance.usuario1 = self.request.user
        return super().form_valid(form)

class ChatList(ListView, LoginRequiredMixin):
    model = Chat
    template_name = 'web_ppal/chat.html'

class ChatDetalle(DetailView, LoginRequiredMixin):
    model = Chat
    template_name = 'web_ppal/chat_detalle.html'

class SendMessage(CreateView, LoginRequiredMixin):
    model = Mensaje
    form_class = MessageForm
    success_url = '../'

    def form_valid(self, form):
        form.instance.emisor = self.request.user
        form.instance.chat_id = self.request.GET.get('chat_id')
        return super().form_valid(form)
    

web_ppal/templates/web_ppal/aboutMe.html
{% extends "acount/padre.html" %}
{% load static %}
{% block aboutMe %}

<section class="py-5">
    <div class="container my-5">
        <div class="row justify-content-center">
            <div class="col-lg-6">
                <h2>Nicolás Quinterno</h2>
                <p class="lead">Mi nombre es Nicolas Quinterno, soy Ingeniero Agrimensor recibido de la Universidad de BUenos Aires en el año 2017, tengo 32 Años y actualmente me desempeño como Subgerente Operativo de registro de Mensuras en el Gobierno de la Ciudad de Buenos Aires, ayudante de catedra de las Materias Agrimensura Legal I y II de la Carrera de Ingeniera en Agrimensura de la UBA, y como profesional independiente en la provincia de Buenos Aires.</p>
                <!-- <p class="mb-0">The universe is almost 14 billion years old, and, wow! Life had no problem starting here on Earth! I think it would be inexcusably egocentric of us to suggest that we're alone in the universe.</p> -->
            </div>
        </div>
    </div>
</section>
<!-- Image element - set the background image for the header in the line below-->
<div class="py-5 bg-image-full" style="background-image: url('https://source.unsplash.com/4ulffa6qoKA/1200x800')">
    <!-- Put anything you want here! The spacer below with inline CSS is just for demo purposes!-->
    <div class="d-flex justify-content-center">
        <img class="imgPersonal"src="{% static 'web_ppal/assets/img_personal.jpg' %}" alt="">
    </div>
</div>
<!-- Content section-->
<section class="py-5">
    <div class="container my-5">
        <div class="row justify-content-center">
            <div class="col-lg-6">
                <h2>Motivacíon</h2>
                <p class="lead">El presente proyecto web desarrollado en Python bajo el framwork django compone la presentacion final del Curso de Python de Coder House, curso que fue realizado con el objetivo de mejorar mis habilidades de programación con el fin de poder aplicar las habilidades adquiridas al sector en el que me desempeño, o bien poder migrar hacia el sector tecnológico</p>
            </div>
        </div>
    </div>
</section>

{% endblock %}

web_ppal/templates/web_ppal/chat.html
{% extends "acount/padre.html" %}
{% load static %}
{% block chat %}

  <div class="container contenido">
    <!-- <div class="row d-flex justify-content-center">
      <h3 class="d-flex m-3 justify-content-center">Chats</h3>
    </div> -->
    <div class="row m-3 d-flex justify-content-center">
      
      <div class="col-3">

      </div>
      <div class="col-6">
        <h3 class="d-flex m-3 justify-content-center">Chats</h3>
      </div>
      <div class="col-3 ">
        <a href="{% url 'web_ppal:NewChat' %}" class="btn btn-success m-3">Nueva Conversación</a>
      </div>

    </div>

    <div class="container">
      {% for chat in object_list %}
      <div class="row m-2 d-flex justify-content-center">
        <div class="card d-flex justify-content-center" style="width: 25rem;">
          <div class="card-body">
            {% if chat.usuario1 == request.user %}
                <h6 class="card-title">{{chat.usuario2}}</h6>
            {% else %}
                <h6 class="card-title">{{chat.usuario1}}</h6>
            {% endif %}
            <a class="btn btn-primary" href="{% url 'web_ppal:DetailChat' chat.id %}">Ver chat</a>
            <!-- <p class="card-text">{{post.texto}}</p> -->
          </div>
        </div>
      </div>
      {% empty %}
      <div class="container">
        <div class="row d-flex justify-content-center">
          <h5 class="d-flex m-3 justify-content-center">No hay Chats Aún</h5>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>

{% endblock %}

web_ppal/templates/web_ppal/chat_detalle.html
{% extends "acount/padre.html" %}
{% load static %}
{% block chat_detalle %}

<div class="row m-2 d-flex justify-content-center">
  <div class="card d-flex justify-content-center" style="width: 100%;">
    <div class="card-body">
      {% if chat.usuario1 == request.user %}
      <h6 class="card-title">{{chat.usuario2}}</h6>
      {% else %}
      <h6 class="card-title">{{chat.usuario1}}</h6>
      {% endif %}
      {% for mensaje in chat.mensajes.all %}
        <div class="row">
          <div class="col-1">
              <p>{{mensaje.emisor}}</p>
          </div>
          <div class="col-2">
            <p>{{mensaje.fecha_envio}}</p>
        </div>
          <div class="col-9">
              <p>{{mensaje.mensaje}}</p>
          </div>

        </div>
      {% empty %}
        <p>No hay mensajes</p>
      {% endfor %}
      <div class="row">
        <div class="col-6">
          <a href="{% url 'web_ppal:send_message'%}?chat_id={{ chat.id }}" class="btn btn-primary">Enviar Mensaje</a>
        </div>
        <div class="col-6">
          <a href="{% url 'web_ppal:Chat' %}" class="btn btn-secondary">Volver</a>
        </div>
      </div>        
    </div>
  </div>
</div>

{% endblock %}

web_ppal/templates/web_ppal/chat_form.html
{% extends "acount/padre.html" %}
{% load static %}
{% block chat_form %}
<div class="container">
    <div class="row m-3 d-flex justify-content-center">
        <h3 class="d-flex m-3 justify-content-center">Nueva Conversación</h3>
    </div>
    <div class="row m-3 text-center">
        <form class="text-center" action="" method="post">{% csrf_token %}
            {{ form.as_p }}
            <input class="btn btn-success" type="submit" value="Crear Chat">
            <a href="{% url 'web_ppal:Chat' %}" class="btn btn-secondary">Volver</a>
        </form>
    </div>
</div>

{% endblock %}

web_ppal/templates/web_ppal/comment_confirm_delete.html
{% extends "acount/padre.html" %}
{% load static %}
{% block comment_delete %}

<form action="" method="post">{% csrf_token %}
    <div class="row">
        <p>¿Seguro que desea eliminar el Comentario "{{ object }}" ?</p>
    </div>

    <input class="btn btn-danger" type="submit" value="Borrar">

</form>


{% endblock %}

web_ppal/templates/web_ppal/comment_form.html
{% extends "acount/padre.html" %}
{% load static %}
{% block comment_form %}
<div class="container">
    <div class="row m-3 d-flex justify-content-center">
        <h3 class="d-flex m-3 justify-content-center">Nuevo comentario</h3>
    </div>
    <div class="row m-3 text-center">
        <form class="text-center" action="" method="post">{% csrf_token %}
            {{ form.as_p }}
            <input class="btn btn-success" type="submit" value="Comentar">
            <a href="{% url 'web_ppal:List' %}" class="btn btn-secondary">Volver</a>
        </form>
    </div>
</div>
{% endblock %}

web_ppal/templates/web_ppal/home.html
{% extends "acount/padre.html" %}
{% load static %}

{% block inicio %}
<section class="py-5">
    <div class="container d-flex justify-content-center my-5">
        <div class="row d-flex justify-content-center">
            <div class="col-lg-12 justify-content-center">
                <h2>Posty</h2>
            </div>
        </div>
    </div>
</section>
<!-- Image element - set the background image for the header in the line below-->
<div class="py-5 bg-image-full" style="background-image: url('https://source.unsplash.com/4ulffa6qoKA/1200x800')">
    <!-- Put anything you want here! The spacer below with inline CSS is just for demo purposes!-->
    <div style="height: 20rem"></div>
</div>
<!-- Content section-->
<section class="py-5">
    <div class="container d-flex justify-content-center my-5">
        <div class="row justify-content-center">
            <div class="col-lg-12">
                <h2></h2>
                <p class="lead">Proyecto final de Python</p>
                <p class="mb-0">Web tipo Blog </p>
            </div>
        </div>
    </div>
</section>

{% endblock %}

web_ppal/templates/web_ppal/mensaje_form.html
{% extends "acount/padre.html" %}
{% load static %}
{% block mensaje_form %}
<div class="container">
    <div class="row m-3 d-flex justify-content-center">
        <h3 class="d-flex m-3 justify-content-center">Nuevo Mensaje</h3>
    </div>
    <div class="row m-3 text-center">
        <form class="text-center" action="" method="post">{% csrf_token %}
            {{ form.as_p }}
            <input class="btn btn-success" type="submit" value="Enviar">
            <a href="{% url 'web_ppal:Chat' %}" class="btn btn-secondary">Volver</a>
            
        </form>
    </div>
</div>

{% endblock %}

web_ppal/templates/web_ppal/post_confirm_delete.html
{% extends "acount/padre.html" %}
{% load static %}
{% block post_delete %}

<form action="" method="post">{% csrf_token %}
    <div class="row">
        <p>¿Seguro que desea eliminar el Post "{{ object }}" ?</p>
    </div>
    <div class="row">
        <input class="btn btn-danger" type="submit" value="Borrar">
    </div>
</form>

{% endblock %}

web_ppal/templates/web_ppal/post_detalle.html
{% extends "acount/padre.html" %}
{% load static %}
{% block post_detalle %}

<div class="row m-2 d-flex justify-content-center">
    <div class="card d-flex justify-content-center" style="width: 25rem;">
      <img src="{{ post.imagen.url }}" class="card-img-top" alt="...">
        <div class="card-body">
            <h6 class="card-title">Autor: {{post.autor_id}}</h6>
            <h5 class="card-title">Título: {{post.titulo}}</h5>
            {% if post.fecha %}
              <p>Fecha: {{ post.fecha }}</p>
            {% endif %}
            <p class="card-text">{{post.texto}}</p>
            <a href="{% url 'web_ppal:List' %}" class="btn btn-secondary">Volver</a>
            <a href="{% url 'web_ppal:NewComment'%}?post_id={{ post.id }}" class="btn btn-primary">Comentar</a>
        </div>
        <h6>Comentarios:</h6>
        <ul>
          {% for comment in post.comments.all %}
            <li>
              <div class="row">
              {{comment.user}}:
              </div>
              <div class="row">
                <p>Fecha: {{ comment.fecha }}</p>
              </div>
              <div class="row">
                {{ comment.comentario }}
              </div>
              {% if comment.user == request.user %}
                <a href="{% url 'web_ppal:EditComment' comment.id %}" class="btn btn-warning">Editar</a>
                <a href="{% url 'web_ppal:DeleteComment' comment.id %}" class="btn btn-danger">Borrar</a>
              {% endif %}

            </li>
          {% empty %}
            <li>No hay comentarios.</li>
          {% endfor %}
        </ul>
    </div>

  </div>

{% endblock %}

web_ppal/templates/web_ppal/post_form.html
{% extends "acount/padre.html" %}
{% load static %}
{% block post_form %}
        <div class="container">
            <div class="row m-3 d-flex justify-content-center">
                <h3 class="d-flex m-3 justify-content-center">Nueva Publicación</h3>
            </div>
            <div class="row m-3 text-center">
                <form class="text-center" action="" method="post" enctype ="multipart/form-data">{% csrf_token %}
                    {{ form.as_p }}
                    <input class="btn btn-success" type="submit" value="Publicar">
                    <a href="{% url 'web_ppal:List' %}" class="btn btn-secondary">Volver</a>
                </form>
            </div>
        </div>
{% endblock %}

web_ppal/templates/web_ppal/post_list.html
{% extends "acount/padre.html" %}
{% load static %}
{% block post_list %}
  <div class="container">
    <div class="row d-flex justify-content-center">
      <h3 class="d-flex m-3 justify-content-center">Publicaciones</h3>
    </div>
  </div>

    <div class="container">
      {% for post in object_list %}
      <div class="row m-2 d-flex justify-content-center">
      <div class="card d-flex justify-content-center" style="width: 25rem;">
        <img src="{{ post.imagen.url }}" class="card-img-top" alt="...">
          <div class="card-body">
            <h6 class="card-title">Autor: {{post.autor_id}}</h6>
            <h5 class="card-title">Título: {{post.titulo}}</h5>
            <!-- <p class="card-text">{{post.texto}}</p> -->
            <a href="{% url 'web_ppal:Detail' post.id %}" class="btn btn-primary">Leer Más</a>
            {% if post.autor_id == request.user %}
              <a href="{% url 'web_ppal:Edit' post.id %}" class="btn btn-warning">Editar</a>
              <a href="{% url 'web_ppal:Delete' post.id %}" class="btn btn-danger">Borrar</a>
            {% endif %}
          </div>
        </div>
      </div>
      {% empty %}
      <div class="container">
        <div class="row d-flex justify-content-center">
          <h5 class="d-flex m-3 justify-content-center">No hay Páginas Aún</h5>
        </div>
      </div>
      {% endfor %}

    </div>

{% endblock %}