acount/urls.py
app_name = 'acount'

from django.contrib import admin
from django.urls import path
import acount.views
from django.contrib.auth.views import LogoutView



urlpatterns = [
    path('accounts/login/',acount.views.login_request,name='Login'),
    path('accounts/signup/',acount.views.register,name='Registro'),
    path('accounts/logout/', LogoutView.as_view(template_name='acount/logout.html'), name='Logout'),
    path('accounts/profile/edit', acount.views.editarPerfil, name="EditarPerfil"),
    path('accounts/profile/avatar',acount.views.editarAvatar,name="EditarAvatar"),
    path('accounts/profile', acount.views.verPerfil, name="VerPerfil"),

]

nquinterno_proy_final/urls.py
from django.contrib import admin
from django.urls import path, include
import web_ppal.views, acount.views
from django.contrib.auth.views import LogoutView
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web_ppal.urls', namespace='web_ppal')),
    path('', include('acount.urls', namespace='acount')),
]

urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

web_ppal/urls.py
app_name = 'web_ppal'
from django.urls import path
import web_ppal.views


urlpatterns = [
    path("",web_ppal.views.inicio, name="Inicio"),
    path("about/",web_ppal.views.aboutMe,name="AboutMe"),
    path("chat",web_ppal.views.ChatList.as_view(),name="Chat"),
    path("pages/",web_ppal.views.PostList.as_view(),name="List"),
    path(r'pages/(?P<pk>)',web_ppal.views.PostDetalle.as_view(),name="Detail"),
    path(r'^nuevo$',web_ppal.views.PostCreacion.as_view(),name="New"),
    path(r'^editar/(?P<pk>\d+)$',web_ppal.views.PostModificar.as_view(),name="Edit"),
    path(r'^borrar/(?P<pk>\d+)$',web_ppal.views.PostBorrar.as_view(),name="Delete"),
    path(r'^nuevoComentario/$',web_ppal.views.CommentCreacion.as_view(),name="NewComment"),
    path(r'^borrarComentario/(?P<pk>\d+)$',web_ppal.views.CommentBorrar.as_view(),name="DeleteComment"),
    path(r'^editarComentario/(?P<pk>\d+)$',web_ppal.views.CommentModificar.as_view(),name="EditComment"),
    path(r'^nuevoChat/$',web_ppal.views.ChatCreacion.as_view(),name="NewChat"),
    path(r'chat^(?P<pk>\d+)$',web_ppal.views.ChatDetalle.as_view(),name="DetailChat"),
    path(r'^EnviarMensaje/$', web_ppal.views.SendMessage.as_view(), name='send_message'),
]

acount/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Avatar(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    # user = models.OneToOneField(User,on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to='avatares', null=True, blank = True)
 
    def __str__(self):
        return f"{self.user.username}"

class Profile(models.Model):
    usuario =  models.ForeignKey(User, on_delete=models.CASCADE,)
    nombre = models.CharField(max_length=40, default="-")
    apellido = models.CharField(max_length=40, default="-")
    descripcion = models.CharField(max_length=250, default="-")
    web = models.URLField(default="-")
    

acount/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from .models import *


class UserViewForm(forms.ModelForm):
    username = forms.CharField()
    class Meta:
        model = User
        fields = ['username', 'email']
    
    def __init__(self, *args, **kwargs):
        super(UserViewForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['readonly'] = True

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    password1 = forms.CharField(label="Contraseña", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Repetir contraseña", widget=forms.PasswordInput)
 
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        # Saca los mensajes de ayuda
        help_texts = {k:"" for k in fields}

class UserEditForm(UserChangeForm):

    # Obligatorios
    email = forms.EmailField(label="Ingrese su email:")
    password1 = forms.CharField(label='Contraseña', widget=forms.PasswordInput, help_text='')
    password2 = forms.CharField(label='Repetir la contraseña', widget=forms.PasswordInput, help_text='')

    class Meta:
        model = User
        fields = ['email', 'password1', 'password2']

class ProfileCreationForm(forms.ModelForm):
    nombre = forms.CharField(max_length=100)
    apellido = forms.CharField(max_length=100)
    descripcion = forms.CharField(widget=forms.Textarea)
    web = forms.URLField()

    class Meta:
        model = Profile
        fields = ['nombre', 'apellido', 'descripcion', 'web']

class ProfileDisplayForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ['nombre', 'apellido', 'descripcion', 'web']

    def __init__(self, *args, **kwargs):
        super(ProfileDisplayForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['readonly'] = True

class FormAvatar(forms.ModelForm):
    imagen = forms.ImageField()
    class Meta:
        model = Avatar
        fields = ['imagen']
    
    

acount/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from .forms import *
from .models import *
from django.contrib.auth.decorators import login_required

def login_request(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data = request.POST)
        print(request.user)
        if form.is_valid():  # Si pasó la validación de Django

            usuario = form.cleaned_data.get('username')
            contrasenia = form.cleaned_data.get('password')
            user = authenticate(username= usuario, password=contrasenia)
            if user is not None:
                login(request, user)
                # try:
                #     avatar = (Avatar.objects.filter(user=request.user.id))
                #     n_img = len(avatar)-1
                #     avatar_url = avatar[n_img].imagen.url
                # except:
                #     avatar_url = "../media/avatares/avatar_anonimo.png"
                return render(request, 'web_ppal/home.html', {"mensaje":f"Bienvenido {usuario}"}) #"url":avatar_url}
            else:
                return render(request, "acount/loginIncorrecto.html", {"form": form, "mensaje":"Usario o contraseña incorrecto"})

        else:
            return render(request, "acount/loginIncorrecto.html", {"form": form, "mensaje":"Usario o contraseña incorrecto"})

    form = AuthenticationForm()

    return render(request, "acount/login.html", {"form": form})

def register(request):
      if request.method == 'POST':

            form = UserRegisterForm(request.POST)
            if form.is_valid():

                  username = form.cleaned_data['username']
                  form.save()
                  return render(request,'web_ppal/home.html' ,  {"mensaje":"Usuario Creado Exitosamente:)"})

      else:
            # form = UserCreationForm()       
            form = UserRegisterForm()     

      return render(request,"acount/registro.html" ,  {"form":form})

@login_required
def editarPerfil(request):
    user = request.user
    try:
        perfil = Profile.objects.get(usuario_id = request.user)
    except:
        perfil =""
    
    if request.method == 'POST':
        if "editDatos" in request.POST:  
            miFormulario = UserEditForm(request.POST)

            if miFormulario.is_valid():
                informacion = miFormulario.cleaned_data
                user.email = informacion['email']
                user.set_password(informacion['password1'])
                user.save()
            return redirect ('/') 
        
        elif "editProfile" in request.POST:
            miFormulario = ProfileCreationForm(request.POST)
            if miFormulario.is_valid():
                informacion = miFormulario.cleaned_data
                if perfil == "":
                    profile =  Profile(usuario = user, nombre = informacion['nombre'], apellido = informacion['apellido'], descripcion = informacion['descripcion'], web = informacion['web'])
                    profile.save()
                elif perfil !=0:
                    profile = Profile.objects.filter(usuario_id = request.user)
                    profile.update(usuario = user, nombre = informacion['nombre'], apellido = informacion['apellido'], descripcion = informacion['descripcion'], web = informacion['web'])
            return redirect ('../../accounts/profile/edit')         
        else:
            pass
    else:
        formDatos = UserEditForm(initial={'email': user.email})
        if perfil != "":
            formProfile = ProfileCreationForm(initial={'nombre':perfil.nombre ,'apellido':perfil.apellido,'descripcion':perfil.descripcion,'web':perfil.web})
        else:
            formProfile =  ProfileCreationForm()
    return render(request, "acount/editarPerfil.html", {"formDatos": formDatos,"formProfile":formProfile ,"usuario": user})


@login_required
def editarAvatar(request):
    if request.method == 'POST':
        form = FormAvatar(request.POST, request.FILES)
        if form.is_valid():
            # u = User.objects.get(username = request.user)
            avatar = Avatar(user = request.user, imagen = form.cleaned_data['imagen'])
            avatar.save()
            return render(request, 'web_ppal/home.html')
    else:
        form = FormAvatar()
    return render(request, 'acount/agregarAvatar.html',{'form':form})

@login_required
def verPerfil(request):
    try:
        profile = Profile.objects.get(usuario = request.user.id)
        formProfile = ProfileDisplayForm(instance=profile)
    except:
        formProfile = ProfileDisplayForm()
    formUser = UserViewForm(instance=request.user)

    return render(request, 'acount/verPerfil.html',{"formUser":formUser, "formProfile":formProfile})

acount/templates/acount/agregarAvatar.html
{% extends "acount/padre.html" %}
{% load static %}
{% block agregarAvatar %}

<div class="mb-3 container">
    <div class="row d-flex justify-content-center">
      <h3 class="d-flex m-3 justify-content-center">Actualizar avatar de: {{user}}</h3>
    </div>
</div>

<form class="mb-3" action="" method="POST" enctype="multipart/form-data">{% csrf_token %}

    <div class="d-flex justify-content-center">

        {{ form.as_p }}

    </div>

    <div class="d-flex mt-3 justify-content-center">
        <input class = "btn btn-success" type="submit", value="Actualizar">
    </div>

</form> 

{% endblock %}

acount/templates/acount/editarPerfil.html
{% extends "acount/padre.html" %}
{% load static %}
{% block editarPerfil %}

    <div class="container">
        <div class="row d-flex justify-content-center">
          <h4 class="d-flex m-3 justify-content-center">Datos de Usuario</h4>
        </div>
    
        <form class="mb-3 text-center" action="" method="POST">{% csrf_token %}
            <div class="d-flex justify-content-center">
                <table>
                    {{ formDatos.as_table }}
                </table>
            </div>

            <div class="d-flex mt-3 justify-content-center">
                <input class="btn btn-success" type="submit" name="editDatos" value="Modificar datos">
            </div>
        </form>
    </div>

    <div class="container">
        <div class="row d-flex justify-content-center">
          <h4 class="d-flex m-3 justify-content-center">Datos de Perfil</h4>
        </div>
        <form class="mb-3 text-center" action="" method="POST">{% csrf_token %}

            <div class="d-flex justify-content-center">
                <table>
                    {{ formProfile.as_table }}
        
                </table>
            </div>

            <div class="d-flex mt-3 justify-content-center">
                <input class="btn btn-success" type="submit" name="editProfile" value="Modificar datos">
            </div>
        </form>
    </div>

    <!-- <div class="container">
        <div class="row d-flex justify-content-center">
          <h4 class="d-flex m-3 justify-content-center">Avatar</h4>
        </div>

        <form class="mb-3 text-center" action="" method="POST" enctype ="multipart/form-data">{% csrf_token %}
            <div class="d-flex justify-content-center">
                <table>
                    {{ formAvatar.as_table }}
                </table>
            </div>

            <div class="d-flex mt-3 justify-content-center">
                <input class="btn btn-success" type="submit" name="editAvatar" value="Modificar Avatar">
            </div>
        </form> 
    </div> -->

{% endblock %}

acount/templates/acount/inicio.html
{% extends "acount/padre.html" %}
{% load static %}
{% block inicio %}
        <!-- Header - set the background image for the header in the line below-->
        <header class="py-5 bg-image-full" style="background-image: url('https://source.unsplash.com/wfh8dDlNFOk/1600x900')">
            <div class="text-center my-5">
                <img class="img-fluid rounded-circle mb-4" src="https://dummyimage.com/150x150/6c757d/dee2e6.jpg" alt="..." />
                <h1 class="text-white fs-3 fw-bolder">Full Width Pics</h1>
                <p class="text-white-50 mb-0">Landing Page Template</p>
            </div>
        </header>
    {% if mensaje %}
    <div class="row">
        <p style="color:rgb(0, 17, 255)">{{mensaje}}</p>
    </div>
    {% endif %}

{% endblock %}

acount/templates/acount/login.html
{% extends "acount/padre.html" %}
{% load static %}
{% block login %}
<div class="login d-flex justify-content-center align-items-center">
    <form action="" method="POST">{% csrf_token %}
        <div class="row">
            <table>
                {{ form.as_table}}
            </table>

        </div>
        <div class="d-flex mt-3 justify-content-center">
            <button type="submit">Iniciar Sesión</button>
        </div>

    </form>
</div>
{% endblock %}

acount/templates/acount/loginIncorrecto.html
{% extends "acount/padre.html" %}
{% load static %}
{% block loginIncorrecto %}
<div class = "mt-3 text-center loginIncorrecto">
    {{mensaje}}
</div>
<div class="d-flex justify-content-center m-3">
    <a class="btn btn-secondary" href="{% url 'acount:Login' %}">Volver al login</a>
</div>

{% endblock %}

acount/templates/acount/logout.html
{% extends "acount/padre.html" %}
{% load static %}
{% block logout %}
<div class="mb-3 mt-3 container">
    <div class="row d-flex justify-content-center">
      <h3 class="text-center">Hasta Pronto</h3>
    </div>
</div>
 
{% endblock%}

acount/templates/acount/padre.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Full Width Pics - Start Bootstrap Template</title>
        <!-- Favicon-->
        {% load static %}
        <link rel="icon" type="image/x-icon" href="{% static 'acount/assets/favicon.ico' %}"/>
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'acount/css/styles.css' %}" rel="stylesheet" />
        <link href="{% static 'acount/css/style_2.css' %}" rel="stylesheet" />
        <link href="{% static 'web_ppal/css/style_2.css' %}" rel="stylesheet" />
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="#!">Posty</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        {% if not request.user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'web_ppal:AboutMe' %}">Sobre mi</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'acount:Login' %}">Ingresa</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'acount:Registro' %}">Registrate</a></li>
                        {% endif %}
                        {% if request.user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'web_ppal:Inicio' %}">Inicio</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'web_ppal:AboutMe' %}">Acerca de mi</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'web_ppal:List' %}">Blog</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'web_ppal:New' %}">Nuevo Posteo</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'web_ppal:Chat' %}">Chat</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><img src="{{ user.avatar_set.last.imagen.url }}" alt="" class="avatar mx-1 my-1">{{request.user}}</a>
                            <ul class="dropdown-menu">
                                
                              <li><a class="dropdown-item" href="{% url 'acount:VerPerfil' %}">Ver Perfil</a></li>
                              <li><a class="dropdown-item" href="{% url 'acount:EditarPerfil' %}">Modificar datos</a></li>
                              <li><a class="dropdown-item" href="{% url 'acount:EditarAvatar' %}">Editar Avatar</a></li>
                              <li><hr class="dropdown-divider"></li>
                              <li><a class="dropdown-item" href="{% url 'acount:Logout' %}">Salir</a></li>
                            </ul>
                          </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
       
        {% block login %}
        {% endblock login %}

        {% block verPerfil %}
        {% endblock verPerfil %}

        {% block editarPerfil %}
        {% endblock editarPerfil %}
        
        {% block inicio %}
        {% endblock inicio %}

        {% block logout %}
        {% endblock logout %}
        
        {% block post_list %}
        {% endblock post_list %}
        
        {% block post_form %}
        {% endblock post_form %}
        
        {% block post_detalle %}
        {% endblock post_detalle %}

        {% block post_delete %}
        {% endblock post_delete %}
        
        {% block comment_form %}
        {% endblock comment_form %}

        {% block comment_delete %}
        {% endblock comment_delete %}

        {% block aboutMe %}
        {% endblock aboutMe %}

        {% block chat %}
        {% endblock chat %}

        {% block chat_form %}
        {% endblock chat_form %}
        
        {% block chat_detalle %}
        {% endblock chat_detalle %}

        {% block mensaje_form %}
        {% endblock mensaje_form %}

        {% block agregarAvatar %}
        {% endblock agregarAvatar %}

        {% block loginIncorrecto %}
        {% endblock loginIncorrecto %}

        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Posty 2023</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static './js/scripts.js' %}"></script>
    </body>
</html>

acount/templates/acount/registro.html
{% extends "acount/padre.html" %}
{% load static %}
{% block login %}
<div class="login d-flex justify-content-center align-items-center">
    <form action="" method="POST">{% csrf_token %}
        <div class="row">
            <table>
                {{ form.as_table}}
            </table>

        </div>
        <div class="d-flex mt-3 justify-content-center">
            <button type="submit">registrarse</button>
        </div>

    </form>
</div>
{% endblock%}

acount/templates/acount/verPerfil.html
{% extends "acount/padre.html" %}
{% load static %}
{% block verPerfil %}
<div class="container">
    <div class="row d-flex justify-content-center">
      <h4 class="d-flex m-3 justify-content-center">Datos de Usuario</h4>
    </div>

    <h3>{{usuario}}</h3>
  
    <div class="d-flex justify-content-center">
        <table>
            <table>
                {{formUser.as_table}}
            </table>
        </table>
    </div>
</div>

<div class="container">
    <div class="row d-flex justify-content-center">
      <h4 class="d-flex m-3 justify-content-center">Datos de Perfil</h4>
    </div>

    <div class="d-flex justify-content-center">
        <table>
            <table>
                {{formProfile.as_table}}
            </table>
        </table>
    </div>
</div>
 
{% endblock %}